image: $CI_REGISTRY/green-everest/system/php:master
cache:
  paths:
    - vendor/

stages:
  - test
  - deploy

before_script:
  - composer install

test:
  stage: test
  script:
    - vendor/bin/phpunit tests/Unit/php

deploy:
  stage: deploy
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data branch=$CI_COMMIT_REF_SLUG "https://git.tonisoftware.de/api/v4/projects/$CI_PROJECT_ID/packages/composer"'

services:
  - mysql:latest

variables:
  # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
  MYSQL_RANDOM_ROOT_PASSWORD: 1
  MYSQL_DATABASE: "lstest"
  MYSQL_USER: "lsuser"
  MYSQL_PASSWORD: "secret"
  DB_HOST: 'mysql:3306'

